spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/ProgettoNegozioScarpe
          issuer-uri: http://localhost:8080/realms/ProgettoNegozioScarpe/protocol/openid-connect/certs
  datasource:
    password: '1002'
    username: postgres
    url: jdbc:postgresql://localhost:5432/ShareSub

  sql:
    init:
      platform: postgres
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_cpntextual_creation: true

server:
  error:
    include-message: always
  port: '8181'
  ssl:
    enabled: false

